version: "3.7"

services:
  risingwave: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    command: >
      standalone
      --meta-opts=" --backend etcd --etcd-endpoints etcd:2388  --listen-addr 0.0.0.0:5690  --advertise-addr 0.0.0.0:5690 --dashboard-host 0.0.0.0:5691 --prometheus-host 0.0.0.0:1250 --prometheus-endpoint http://prometheus:9500 --state-store hummock+minio://hummockadmin:hummockadmin@minio:9000/hummock001 --data-directory hummock_001 --connector-rpc-endpoint 0.0.0.0:50051" 
      --frontend-opts=" --listen-addr 0.0.0.0:4566 --health-check-listener-addr 0.0.0.0:6786 --prometheus-listener-addr 0.0.0.0:1250 --advertise-addr 0.0.0.0:4566 --meta-addr http://0.0.0.0:5690 "  
      --compute-opts="--listen-addr 0.0.0.0:5688 --advertise-addr 0.0.0.0:5688 --prometheus-listener-addr 0.0.0.0:1250 --async-stack-trace verbose --connector-rpc-endpoint 0.0.0.0:50051 --role both --meta-address http://0.0.0.0:5690"  
      --compactor-opts=" --listen-addr 0.0.0.0:6660  --prometheus-listener-addr 0.0.0.0:1250 --advertise-addr 0.0.0.0:6660 --meta-address http://0.0.0.0:5690"

    ports:
      - "4566:4566"
      - "5691:5691"

  minio: # object store for risingwave
    image: quay.io/minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data/hummock001 && minio server /data'
    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - "minio-data:/data"
    environment:
      MINIO_ROOT_PASSWORD: hummockadmin
      MINIO_ROOT_USER: hummockadmin
      MINIO_CONSOLE_ADDRESS: 0.0.0.0:9001

  etcd: # Key value store for metadata of risingwave
    image: "quay.io/coreos/etcd:v3.5.10"

    volumes:
      - "etcd-data:/etcd-data"
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2388
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2388
      ETCD_NAME: risedev-meta
      ETCD_DATA_DIR: /etcd-data
      ETCD_AUTO_COMPACTION_MODE: periodic
      ETCD_AUTO_COMPACTION_RETENTION: 1m

  prometheus:
    image: "prom/prometheus:latest"
    command: >
      --config.file=/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.listen-address=0.0.0.0:9500
      --storage.tsdb.retention.time=30d
    ports:
      - "9500:9500"
    volumes:
      - "prometheus-data:/prometheus"

  grafana:
    image: "grafana/grafana-oss:latest"
    ports:
      - "3001:3001"
    volumes:
      - "grafana-data:/var/lib/grafana"

    environment:
      GF_PATHS_CONFIG: /var/lib/grafana/grafana.ini
      GF_PATHS_PROVISIONING: /var/lib/grafana/provisioning
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/provisioning/dashboards/grafana-risedev-dashboard.yml

volumes:
  minio-data:
  etcd-data:
  prometheus-data:
  grafana-data: